__title__ = 'MindsDB Apache Pinot handler'
__package_name__ = 'mindsdb_pinot_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Apache Pinot"
__author__ = 'Minura Punchihewa'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
