# Shop is a singleton resource (not a paginated connection).
# The custom list() implementation in shopify_tables.py returns a single row.

columns = [
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "id",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "A globally-unique ID.",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "name",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The name of the shop.",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "email",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The contact email address for the shop.",
        "IS_NULLABLE": True,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "contactEmail",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The contact email address for the shop owner.",
        "IS_NULLABLE": True,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "myshopifyDomain",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The .myshopify.com domain of the shop.",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "primaryDomain",
        "DATA_TYPE": "JSON",
        "COLUMN_DESCRIPTION": "The primary domain of the shop (host and url).",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "plan",
        "DATA_TYPE": "JSON",
        "COLUMN_DESCRIPTION": "The shop's subscription plan (displayName, partnerDevelopment, shopifyPlus).",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "currencyCode",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The shop's currency code.",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "currencyFormats",
        "DATA_TYPE": "JSON",
        "COLUMN_DESCRIPTION": "The shop's currency formats.",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "timezoneAbbreviation",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The shop's timezone abbreviation.",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "timezoneOffset",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The shop's timezone offset (e.g. -05:00).",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "ianaTimezone",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The IANA timezone of the shop (e.g. America/New_York).",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "description",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The shop's description.",
        "IS_NULLABLE": True,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "url",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The public URL of the shop.",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "createdAt",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The date and time when the shop was created.",
        "IS_NULLABLE": False,
    },
    {
        "TABLE_NAME": "shop",
        "COLUMN_NAME": "updatedAt",
        "DATA_TYPE": "TEXT",
        "COLUMN_DESCRIPTION": "The date and time when the shop was last updated.",
        "IS_NULLABLE": False,
    },
]
