__title__ = 'MindsDB TimeScaleDB handler'
__package_name__ = 'mindsdb_timescaledb_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for TimeScaleDB"
__author__ = 'Parthiv MAkwana'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
