__title__ = 'MindsDB Serpstack handler'
__package_name__ = 'mindsdb_serpstack_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Serpstack API"
__author__ = 'Anders Ooi'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024 - mindsdb'
