__title__ = 'MindsDB TPOT handler'
__package_name__ = 'mindsdb_tpot_handler'
__version__ = '0.0.2'
__description__ = "MindsDB handler for TPOT "
__author__ = 'Parthiv Makwana'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
