DROP DATABASE IF EXISTS MDB_DB_HANDLER_TEST;
CREATE DATABASE MDB_DB_HANDLER_TEST;

USE MDB_DB_HANDLER_TEST;


CREATE TABLE TEST (COL_ONE INT, COL_TWO INT, COL_THREE FLOAT, COL_FOUR VARCHAR(20));


INSERT INTO TEST (COL_ONE, COL_TWO, COL_THREE, COL_FOUR) VALUES (1, -1, 0.1, 'A');
INSERT INTO TEST (COL_ONE, COL_TWO, COL_THREE, COL_FOUR) VALUES (2, -2, 0.2, 'B');
INSERT INTO TEST (COL_ONE, COL_TWO, COL_THREE, COL_FOUR) VALUES (3, -3, 0.3, 'C');
