__title__ = 'MindsDB Google Content API for Shopping handler'
__package_name__ = 'mindsdb_google_content_shopping_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for the Google Content API for Shopping"
__author__ = 'Panagiotis-Alexios Spanakis'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - mindsdb'
