# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mindsdb.grpc.db.db_pb2 as db__pb2


class DBServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckConnection = channel.unary_unary(
                '/DBService/CheckConnection',
                request_serializer=db__pb2.HandlerContext.SerializeToString,
                response_deserializer=db__pb2.StatusResponse.FromString,
                )
        self.NativeQuery = channel.unary_unary(
                '/DBService/NativeQuery',
                request_serializer=db__pb2.NativeQueryContext.SerializeToString,
                response_deserializer=db__pb2.Response.FromString,
                )


class DBServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NativeQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckConnection,
                    request_deserializer=db__pb2.HandlerContext.FromString,
                    response_serializer=db__pb2.StatusResponse.SerializeToString,
            ),
            'NativeQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.NativeQuery,
                    request_deserializer=db__pb2.NativeQueryContext.FromString,
                    response_serializer=db__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DBService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DBService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBService/CheckConnection',
            db__pb2.HandlerContext.SerializeToString,
            db__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NativeQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBService/NativeQuery',
            db__pb2.NativeQueryContext.SerializeToString,
            db__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
