__title__ = 'MindsDB Zotero handler'
__package_name__ = 'mindsdb_zotero_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Zotero"
__author__ = 'Elina Kapetanaki'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024 - mindsdb'
