__title__ = 'MindsDB Binance handler'
__package_name__ = 'mindsdb_binance_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for the Binance API"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - mindsdb'
