__title__ = 'MindsDB CKAN handler'
__package_name__ = 'mindsdb_ckan_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for CKAN"
__author__ = 'Konstantin Sivakov'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
