[pytest]
filterwarnings =
    # Ignore all DeprecationWarnings
    ignore::DeprecationWarning
    # Ignore specific UserWarnings from pydantic
    ignore:Field "model_name" in LLMConfig has conflict with protected namespace "model_":UserWarning
    ignore:Field "model_name" in ClovaXEmbeddings has conflict with protected namespace "model_":UserWarning
    # Ignore specific PendingDeprecationWarnings
    ignore:Please use `import python_multipart` instead.:PendingDeprecationWarning