__title__ = 'MindsDB Leonardo AI Handler'
__package_name__ = 'mindsdb_leonardo_ai_handler'
__version__ = '0.0.1'
__description__ = "MindsDB Handler for Leonardo AI"
__author__ = 'Tarun Chawla'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - mindsdb'
