__title__ = 'MindsDB Cassandra handler'
__package_name__ = 'mindsdb_cassandra_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for CassandraDB"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2022- mindsdb'
