__title__ = 'MindsDB Jira handler'
__package_name__ = 'mindsdb_jira_handler'
__version__ = '0.0.2'
__description__ = "MindsDB handler for Jira"
__author__ = 'Balaji Seetharaman'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
