__title__ = 'MindsDB DuckDuckGo Handler'
__package_name__ = 'mindsdb_duckduckgo_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for the DuckDuckGo Zero-click Info API"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - MindsDB'