__title__ = 'MindsDB Google Analytics handler'
__package_name__ = 'mindsdb_google_analytics_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Google Analytics"
__author__ = 'Talaat Hasanin'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
