__title__ = 'MindsDB Twilio handler'
__package_name__ = 'mindsdb_twilio_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Twilio"
__author__ = 'Lizzie Siegle'
__github__ = 'https://github.com/elizabethsiegle'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
