__title__ = 'MindsDB Azure Blob Storage handler'
__package_name__ = 'mindsdb_azure_blob_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Azure Blob Storage"
__author__ = 'Fabian Jevon'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024- mindsdb'
