__title__ = 'MindsDB pytorch tabular handler'
__package_name__ = 'pytorch_tabular_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for PyTorch Tabular"
__author__ = 'Pranav Prajapati'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2023 - mindsdb'