__title__ = 'MindsDB Newa APi handler'
__package_name__ = 'mindsdb_news_api_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for News API"
__author__ = 'Thimotee Kenmogne'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
