__title__ = 'MindsDB Google Cloud Storage handler'
__package_name__ = 'mindsdb_google_cloud_storage_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for the Google Cloud Storage"
__author__ = 'Viktoria Lukacova'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - mindsdb'
