__title__ = 'MindsDB Xero handler'
__package_name__ = 'mindsdb_xero_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for the Xero Accounting API"
__author__ = 'MindsDB'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2025 - mindsdb'
