__title__ = 'MindsDB CoinMarketCap handler'
__package_name__ = 'mindsdb_coinmarketcap_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for CoinMarketCap"
__author__ = 'YourName'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2025- mindsdb'