__title__ = 'MindsDB Dremio handler'
__package_name__ = 'mindsdb_dremio_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Dremio"
__author__ = 'Minura Punchihewa'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
