__title__ = 'MindsDB Empress Embedded handler'
__package_name__ = 'mindsdb_empress_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Empress Embedded"
__author__ = 'Panagiotis-Alexios Spanakis and Theodoros Malikourtis'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
