__title__ = 'MindsDB Lightwood handler'
__package_name__ = 'mindsdb_lightwood_handler'
__version__ = '1.0.0'
__description__ = "MindsDB handler for Lightwood"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2022- mindsdb'
