__title__ = 'MindsDB SAP MaxDB handler'
__package_name__ = 'mindsdb_maxdb_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for SAP MAXDB"
__author__ = 'Marsid Mali & Sergi Poula'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
