__title__ = 'MindsDB Google Ads handler'
__package_name__ = 'mindsdb_google_ads_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Google Ads"
__author__ = 'Talentify'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024- mindsdb'
