__title__ = "MindsDB Microsoft One Drive handler"
__package_name__ = "mindsdb_ms_one_drive_handler"
__version__ = "0.0.1"
__description__ = "MindsDB handler for Microsoft One Drive"
__author__ = 'MindsDB Inc'
__github__ = "https://github.com/mindsdb/mindsdb"
__pypi__ = "https://pypi.org/project/mindsdb/"
__license__ = "MIT"
__copyright__ = "Copyright 2024 - mindsdb"
