__title__ = 'MindsDB LlamaIndex Github handler'
__package_name__ = 'mindsdb_llama_index_github_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for LlamaIndex Github loader"
__author__ = 'Pranav Prajapati'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - mindsdb'