__title__ = 'MindsDB Unify handler'
__package_name__ = 'mindsdb_unify_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Unify"
__author__ = 'Janice Herman & Mohamed Abderrahim'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024 - mindsdb'
