__title__ = 'MindsDB'
__package_name__ = 'mindsdb'
__version__ = '2.2.0'
__description__ = "MindsDB server, provides server capabilities to mindsdb native python library"
__email__ = "jorge@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018- mindsdb'
