__title__ = 'MindsDB'
__package_name__ = 'mindsdb'
__version__ = '1.2.8'
__description__ = "MindsDB's goal is to make it very simple for developers to use the power of artificial neural networks in their projects."
__email__ = "jorge@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018- mindsdb'
