__title__ = 'MindsDB Financial Modeling Prep handler'
__package_name__ = 'mindsdb_financial_modeling_prep_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Financial Modeling Prep API"
__author__ = 'Riyana Dutta'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024- mindsdb'
