__title__ = 'MindsDB Rockset handler'
__package_name__ = 'mindsdb_rockset_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Rockset"
__author__ = 'Alissa Troiano'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
