__title__ = 'MindsDB MLflow handler'
__package_name__ = 'mindsdb_mlflow_handler'
__version__ = '0.0.2'
__description__ = "MindsDB handler for MLflow"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
