__title__ = 'MindsDB Amazon Athena handler'
__package_name__ = 'mindsdb_athena_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Amazon Athena"
__author__ = 'Ryan Watts'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
