__title__ = 'MindsDB SurrealDB handler'
__package_name__ = 'mindsdb_surrealdb_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for SurrealDB"
__author__ = 'Emmanouil Dellatolas & Georgios Artopoulos'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
