__title__ = 'MindsDB HSQLDB handler'
__package_name__ = 'mindsdb_hsqldb_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for HSQLDB"
__author__ = 'Enrique Atayde'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
