__title__ = 'MindsDB GCS handler'
__package_name__ = 'mindsdb_gcs_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Google Cloud Storage"
__author__ = 'Abhilash K R'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
