__title__ = 'MindsDB Portkey handler'
__package_name__ = 'mindsdb_portkey_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Portkey"
__author__ = 'Naren Gogineni'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024 - mindsdb'
