__title__ = 'MindsDB PirateWeather API handler'
__package_name__ = 'mindsdb_pirateweather_api_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for the PriateWeather API"
__author__ = 'Patrick Sean Klein'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
