__title__ = 'MindsDB MySQL connector'
__package_name__ = 'mindsdb'
__version__ = '0.0.1'
__description__ = "Connector to MLflow"
__email__ = "jorge@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2018- mindsdb'
