__title__ = 'MindsDB Spacy handler'
__package_name__ = 'mindsdb_spacy_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Spacy"
__author__ = 'Ton Hoang Nguyen (Bill)'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
