__title__ = 'MindsDB Apache Doris handler'
__package_name__ = 'mindsdb_apache_doris_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Apache Doris"
__author__ = 'Aditya Azad'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
