__title__ = 'MindsDB Google Calendar handler'
__package_name__ = 'mindsdb_google_calendar_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for the Google Calendar API"
__author__ = 'Panagiotis-Alexios Spanakis'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - mindsdb'
