__title__ = 'MindsDB Gmail handler'
__package_name__ = 'mindsdb_gmail_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Gmail"
__author__ = 'Rajeev R Sharma and Marios Ajdini'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
