__title__ = 'MindsDB Nuo DB handler'
__package_name__ = 'mindsdb_nuodb_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Nuo DB"
__author__ = 'Kavel Baruah'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
