__title__ = 'MindsDB Merlion handler'
__package_name__ = 'mindsdb_merlion_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Merlion"
__author__ = 'Franklin Zhi'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2022- mindsdb'
