"""view_integration_id

Revision ID: f50c0055539e
Revises: d74c189b87e6
Create Date: 2022-06-07 11:53:41.660414

"""
from alembic import op
import sqlalchemy as sa
import mindsdb.interfaces.storage.db



# revision identifiers, used by Alembic.
revision = 'f50c0055539e'
down_revision = 'd74c189b87e6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.alter_column('integration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('unique_view_name_company_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_view_name_company_id', ['name', 'company_id'])
        batch_op.alter_column('integration_id',
               existing_type=sa.INTEGER(),
               nullable=False)

