"""json_storage

Revision ID: cada7d2be947
Revises: 3d5e70105df7
Create Date: 2022-09-29 15:52:32.695026

"""
from alembic import op
import sqlalchemy as sa
import mindsdb.interfaces.storage.db


# revision identifiers, used by Alembic.
revision = 'cada7d2be947'
down_revision = '3d5e70105df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('json_storage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('resource_group', sa.String(), nullable=True),
        sa.Column('resource_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('content', sa.JSON(), nullable=True),
        sa.Column('company_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('json_storage')
    # ### end Alembic commands ###
