"""predictor_version

Revision ID: 1e60096fc817
Revises: 43c52d23845a
Create Date: 2022-11-07 16:43:47.301692

"""
from alembic import op
import sqlalchemy as sa
import mindsdb.interfaces.storage.db



# revision identifiers, used by Alembic.
revision = '1e60096fc817'
down_revision = '43c52d23845a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictor', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('label')

    # ### end Alembic commands ###
