"""add llm data

Revision ID: 2638b7a5b8aa
Revises: 9461892bd889
Create Date: 2024-05-01 16:41:57.614371

"""
from alembic import op
import sqlalchemy as sa
import mindsdb.interfaces.storage.db  # noqa



# revision identifiers, used by Alembic.
revision = '2638b7a5b8aa'
down_revision = '9461892bd889'
branch_labels = None
depends_on = None


def upgrade():

        # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
            'llm_data',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('input', sa.String(), nullable=False),
            sa.Column('output', sa.String(), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now()),
            sa.PrimaryKeyConstraint('id')
        )


def downgrade():
    op.drop_table('llm_data')
