__title__ = 'Darts Handler'
__package_name__ = 'mindsdb_darts_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Darts"
__author__ = 'lazyMonk'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2022- mindsdb'
